version: '3'
services:
  mysql:
    container_name: daangn-price-mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: daangn
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: daangn
      MYSQL_PASSWORD: hihiboss
    ports:
      - 3306:3306

  daangn-price-api:
    container_name: daangn-price-api
    image: hihiboss/daangn-price-api:latest
    entrypoint:
      - java
      - -jar
      - -Dspring.profiles.active=prod
      - daangn-price-api.jar
    depends_on:
      - mysql