version: '3'
services:
  mariadb:
    container_name: daangn-price-mariadb
    image: mariadb:10.3
    environment:
      MYSQL_DATABASE: daangn
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: daangn
      MYSQL_PASSWORD: hihiboss
      TZ: "Asia/Seoul"
      SYMFONY__ENV__DATABASE_CHARSET: utf8mb4
    volumes:
      - /home/ec2-user/database/daangn-price-api:/var/lib/mysql
    command: --character_set_client=utf8 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --character-set-client-handshake=FALSE
    ports:
      - 3306:3306

  daangn-price-api:
    container_name: daangn-price-api
    image: hihiboss/daangn-price-api:latest
    entrypoint:
      - java
      - -jar
      - -Dspring.profiles.active=prod
      - daangn-price-api.jar
    depends_on:
      - mariadb
    ports:
      - 18080:18080
