server:
  port: 18080

daangn:
  url: https://www.daangn.com/search/
  max-page: 5
  timeout: 1000

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:daangn-price-api
    username: sa
    password:

---
spring:
  profiles: test

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:daangn-price-api
    username: sa
    password:

---
spring:
  profiles: prod

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/daangn
    username: daangn
    password: hihiboss
    hikari:
      auto-commit: false
      idle-timeout: 10000
      minimumIdle: 30
      maximum-pool-size: 150
      read-only: false
      connection-timeout: 20000

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

server:
  port: 18080