server:
  port: 18080

daangn:
  url: https://www.daangn.com/search/
  max-page: 5
  timeout: 1000

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev


---
spring:
  profiles: test


---
spring:
  profiles: prod