server:
  port: 18080

daangn:
  url: https://www.daangn.com/search/
  max-page: 5
  timeout: 1000

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:daangn-price-api
    username: sa
    password:

---
spring:
  profiles: test


---
spring:
  profiles: prod